### ISSUE TITLE
[plugin-publish] Request to publish a new plugin 'HyperProtect DBaaS'

### ISSUE THREAD

**Issue by shwneo** [IBM-Cloud/ibm-cloud-cli-sdk#128]
- name: Hyperprotected DBaaS
  description: Manage your HyperProtect DBaaS Clusters on IBM z Systems via CLI tool.
  company: IBM
  authors:
  - name: Huawei Shen
    contact: bjhwshen@cn.ibm.com
  homepage: https://console.stage1.bluemix.net/docs/services/hypersecure-dbaas/index.html
  version: 0.10.11
  binaries:
  - platform: osx
    url: https://api.hypersecuredbaas.ibm.com/dbaas_cli/v0.10.11/dbaas-macos-0.10.11
    checksum: 8c0954069b726a2225095ec010880addbfcfb11a
  - platform: win64
    url: https://api.hypersecuredbaas.ibm.com/dbaas_cli/v0.10.11/dbaas-win_x86_64-0.10.11.exe
    checksum: acfe58a592109d490c7048bafe5072081b9bc1e5
  - platform: linux32
    url: https://api.hypersecuredbaas.ibm.com/dbaas_cli/v0.10.11/dbaas-linux_i386-0.10.11
    checksum: 89920ab54088b3a8ed6b99e2f71f6d6fbb52a309
  - platform: linux64
    url: https://api.hypersecuredbaas.ibm.com/dbaas_cli/v0.10.11/dbaas-linux_x86_64-0.10.11
    checksum: a02342d4a8ad51367e30422153e16714d1b8c5d7

**Comment by wenygao** [comment]
Another question, regarding the url for the repository, it must be a public repository, or a internal repository is also okey like below: 

https://github.ibm.com/DBaaS-on-z/dbaas-cli/releases/download/0.10.11/dbaas-linux_i386-0.10.11

**Comment by shwneo** [comment]
@boyang9527 Why close this request without any comment? Do we have other way to publish our plugin?
