### ISSUE TITLE
provide API to invoke CF CLI

### ISSUE THREAD

**Issue by archerzz** [IBM-Cloud/ibm-cloud-cli-sdk#13]
# Requirement
In latest version, we remove explicit dependency on CF CLI. However, some plugins requires CF CLI as well. Some of them invoke the CF CLI directly from environment, like below:
```go
os.exec("cf push")
```
Such codes depend on the assumption that users will install a CF CLI, which is not valid any more.

# Solution
We should consider whether to provide an API to invoke the CF CLI:
1. Invoke embedded CF CLI
2. Invoke CF CLI on $PATH if 1 fails.
[optional] provide option to reverse the invocation sequence.

**Comment by weieigao** [comment]
They can still invoke the embedded CF, for example `bx cf push`

**Comment by boyang9527** [comment]
we don't need 2 ... just provide a way to invoke embedded cf with input and output buffer

**Comment by weieigao** [comment]
@boyang9527  If the plugin used to call `cf`, now it should call `bx cf` instead:

```go
cmd := exec.Command("bx", "cf")
in := new(bytes.Buffer)
cmd.Stdin = in
out := new(bytes.Buffer)
cmd.Stdout = out
err := cmd.Run()
```

However, If we want flexibility and transparency, we can provide an API for plugin to invoke bx cli's core command (not restricted to `bx cf`)

**Comment by boyang9527** [comment]
I agree we can make it general ....
