### ISSUE TITLE
Publish csutils plugin to repository

### ISSUE THREAD

**Issue by rjminsha** [IBM-Cloud/ibm-cloud-cli-sdk#138]
- name: csutil
  description: A utility plugin for IBM Service Teams to configure Kubernetes clusters to meet IBM One Cloud Standards.  
  company: IBM
  authors:
  - name: Robbie Minshall
    contact: rjminsha@us.ibm.com
  homepage: https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/W50576e433cea_4fbb_84ed_ec8a855405e4/page/Armada%20Customers
  version: 0.2.4
  binaries:
  - platform: osx
    url: https://github.ibm.com/ibmcloud/ArmadaClusterSetupCLI/releases/download/v0.2.4/csutil-darwin-amd64
    checksum: 551bac484709d600451a6e9c686a6a34
  - platform: win32
    url: https://github.ibm.com/ibmcloud/ArmadaClusterSetupCLI/releases/download/v0.2.4/csutil-win-386.exe
    checksum: 719d11397169e7abb275528c118ef915
  - platform: win64
    url: https://github.ibm.com/ibmcloud/ArmadaClusterSetupCLI/releases/download/v0.2.4/csutil-win-amd64.exe
    checksum: 9740ed42cdec75fa637f59c971f703cc
  - platform: linux32
    url: https://github.ibm.com/ibmcloud/ArmadaClusterSetupCLI/releases/download/v0.2.4/csutil-linux-386
    checksum: ff179cc73edf954ae05bddb1180f27fd
  - platform: linux64
    url: https://github.ibm.com/ibmcloud/ArmadaClusterSetupCLI/releases/download/v0.2.4/csutil-linux-amd64
    checksum: d03a4a1c7f7d30c6b92a24650446d06d

**Comment by rjminsha** [comment]
This plugin is used by IBM teams.  Should this be publishing just to staging repository.

**Comment by weieigao** [comment]
@rjminsha  I left you a message in slack. We have a Jenkins job to do that, also you can contact @archerzz for help
