### ISSUE TITLE
ChoicePrompt should provide a way to return index of chosen item

### ISSUE THREAD

**Issue by archerzz** [IBM-Cloud/ibm-cloud-cli-sdk#15]
# Description
It vey common that for a list of choices, the labels of each choice is different from the value. A common use case of ChoicePrompt is like below
```go
index, err := terminal.ui.NewChoicePrompt("Please select one:", choices, &terminal.PromptOptions{....}).ResolveChoice()
if err != nil {
    return err
}
switch(index) {
    case XXX:
        ...
}
```

**Comment by weieigao** [comment]
ChoicePrompt returns the value not the label...

But it makes sense to support arbitrary value instead of string value only.
