### ISSUE TITLE
Expose CFEE information in plugin context

### ISSUE THREAD

**Issue by steven-crespo** [IBM-Cloud/ibm-cloud-cli-sdk#157]
I need a few methods and variables available in the plugin context that currently only exist in the core cli. I would like access to the following:

- The `HasTargetedCFEE` function
- The `CFEEEnvID` variable

Any other CFEE related variables that you think are good to expose would also be appreciated

**Comment by slc7035** [comment]
@weieigao do you have any estimate of when you will work on this? I need these exposed for the next release of the CFEE plugin which will be in the middle of December.

**Comment by weieigao** [comment]
@slc7035 `HasTargetedCFEE()` is alreaday added int PluginContext in`dev` branch.
For CFEE envID, currently CLI doesn't save the variable when user targets a CFEE instance (ie `ibmcloud target --cf`), but only save it as a cache for CFEE commands only, so we didn't expose the variable in PluginContext.
