### ISSUE TITLE
Does plugin.Namespace Aliases work?

### ISSUE THREAD

**Issue by maxwheel** [IBM-Cloud/ibm-cloud-cli-sdk#217]
When I defined a Namespace aliases, there were error message when installing the plugin:
```
FAILED
Namespace 'oss sh' in the plug-in being installed is not recognized. Ensure it's defined.
```

The code was like
```
[]plugin.Namespace{
		plugin.Namespace{
			Name:        "oss sh",
			Aliases:     []string{"oss selfhealing"},
			Description: "selfhealing commands",
		},
	}
```

If I commented the Aliases line, it works well.

anything wrong?

**Comment by weieigao** [comment]
Nested namespace definition should be like this:
```
[]plugin.Namespace{
               plugin.Namespace{
                        ParentName: "oss",
		},
		plugin.Namespace{
                        ParentName: "oss",
			Name:        "sh",
			Aliases:     []string{"selfhealing"},
			Description: "selfhealing commands",
		},
	}
```

**Comment by maxwheel** [comment]
> Nested namespace definition should be like this:
> 
> ```
> []plugin.Namespace{
>                plugin.Namespace{
>                         ParentName: "oss",
> 		},
> 		plugin.Namespace{
>                         ParentName: "oss",
> 			Name:        "sh",
> 			Aliases:     []string{"selfhealing"},
> 			Description: "selfhealing commands",
> 		},
> 	}
> ```

Thanks so much!

**Comment by maxwheel** [comment]
@weieigao but then I meet a problem in defining commands.
If I use
```
{
			Namespace:   "oss sh",
			Name:        "hello",
},
```
The help message could be shown, but `ibm oss sh hello` will not trigger anything. The code in Run() does not work. 

If I use:
```
{
			Namespace:   "sh",
			Name:        "hello",
},
```
it will report failed when installing the plugin `Namespace 'sh' in the plug-in being installed is not recognized. Ensure it's defined.`.

Could you please help?

**Comment by archerzz** [comment]
Closing since the question is resolved. Thanks @weieigao
