### ISSUE TITLE
Bug: ibmcloud plugin update

### ISSUE THREAD

**Issue by sreeteja7** [IBM-Cloud/ibm-cloud-cli-sdk#242]
So update -r flag is not case sensitive BUT it is trying to fetch information from the actual repo here in our case 'test' BUT displaying in the console message as the parameter that is passed 'TEst'

Same dont apply for the plugin that is upgraded

<img width="1071" alt="Screenshot 2021-03-16 at 10 31 06 PM" src="https://user-images.githubusercontent.com/26268079/111349727-665d8f00-86a7-11eb-80ef-b7b2f5a312bc.png">
It will be nice to have the case insensitive repo parameter also printed likewise

**Comment by boyang9527** [comment]
Thanks for reporting the defect!
I am going to close this issue since it is not related to SDK.  I have moved this issue to the IBM cloud CLI repository and we will address it there.

**Comment by sreeteja7** [comment]
@boyang9527 Please share the ticket details here. Thanks :)

**Comment by sreeteja7** [comment]
I created one https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/154
