### ISSUE TITLE
ibmcloud cli doesn't show portable storage volumes

### ISSUE THREAD

**Issue by akashrajkn** [IBM-Cloud/ibm-cloud-cli-sdk#301]
Hi, I created a block volume and a portable storage volume (Classic >> Block Storage).

I used this command to list all available block volumes: 
```
ibmcloud sl block volume-list 
```
With this I can only view the block volumes. How do I access my portable storage volumes (and attach them via cli)?
ibmcloud version: `2.4.0+4ca2c74-2022-01-20T18:32:41+00:00`

Thanks in advance

**Comment by allmightyspiff** [comment]
The CLI doesn't manage mounting block storage volumes to a host OS.

You can authorize a host to have access to a volume though ( https://cloud.ibm.com/docs/BlockStorage?topic=cli-sl-block-storage&interface=ui#sl_block_access_authorize )

You can find the documentation for Block Storage here: https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-managingstorage&interface=ui  which has some information on how to mount a volume.

**Comment by akashrajkn** [comment]
Thanks for the reply :)

With regard to mounting/attaching, I understand that has be done on the system :)

For reference: I managed to get the list of portable storage volumes like this:
```
ibmcloud sl call-api SoftLayer_Account getBlockStorageVolumes
```
