### ISSUE TITLE
ibmcloud cli - How do I get user notes for a volume?

### ISSUE THREAD

**Issue by akashrajkn** [IBM-Cloud/ibm-cloud-cli-sdk#302]
Hi, with respect to classic infrastructure:
On the ibm cloud console, after creating a file storage unit, I can edit a field called "notes". I use this to get an overview of the volume's purpose.  How do I get the user "notes" for a file storage instance from the cli? When I run the command: 

```
ibmcloud sl file volume-detail <file_storage_id>
```

I get id, username, type, etc. but not "notes"

**Comment by jorge-ibm** [comment]
@allmightyspiff is this something you can answer ?

**Comment by allmightyspiff** [comment]
I'll add this as a feature request for a future version. Also, I please open issues relating to the `ibmcloud sl` command here: https://github.com/softlayer/softlayer-cli and that will notify me. 

https://github.ibm.com/SoftLayer/softlayer-cli/issues/197 For reference

If you need to see the notes for a storage volume, you can use 

```
ibmcloud.exe  sl call-api SoftLayer_Network_Storage getObject --init <file_storage_id>
```

Or use the [`slcli`](https://github.com/softlayer/softlayer-python) which has this feature already.

Hope that helps answer your question.

**Comment by akashrajkn** [comment]
Thank you for the reply.

Using the `ibmcloud sl call-api` command, I was able to get notes which answers my question. 

> I'll add this as a feature request for a future version. Also, I please open issues relating to the `ibmcloud sl` command here: https://github.com/softlayer/softlayer-cli and that will notify me.
I will close this issue and create an issue in the softlayer-cli github repo since https://github.ibm.com/SoftLayer/softlayer-cli/issues/197 is not accessible for me
