### ISSUE TITLE
ibmcloud oc clusters does not work on json formatted output

### ISSUE THREAD

**Issue by SRodi** [IBM-Cloud/ibm-cloud-cli-sdk#351]
## Issue
The command `ibmcloud oc clusters` provides a list of clusters for the account. The command accepts flag `--output` (same as most ibmcloud commands). But for the oc plugin the `--output json` does not work as expected.

## Steps to reproduce

Run without output flag:
```bash
$ ibmcloud oc clusters
OK
Name                    ID                     State    Created        Workers   Location   Version                 Resource Group Name   Provider
my-cluster   c1234cld0sur3m5g   normal   5 months ago   35        Frankfurt     4.9.49_1561_openshift   my-group      my-prov
```

Run with flag:
```bash
$ ibmcloud oc clusters --output json
[]%
```

## Expected behavior

The command ` ibmcloud oc clusters --output json` should return a list of json objects with each (if any) available clusters' details.

**Comment by JohnStarich** [comment]
Hey @SRodi, this is known problem and it's unfortunately tied to backward compatibility (for now anyway). 

From the help text:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/1009441/199809163-e41dff62-0dc2-4fa6-bb96-377d9c96190f.png">

At least for `ks` plugin `v1.x.y`, you'll need to use `--provider` to select the infrastructure provider you'd like to get JSON for. It returns `classic` by default.
