### ISSUE TITLE
Install to $HOME

### ISSUE THREAD

**Issue by karltk** [IBM-Cloud/ibm-cloud-cli-sdk#43]
Please add an option in the `install_bluemix_cli` installer script to install to `$HOME` without requiring root access.

`$HOME/.local/bin` etc, is a well-established convention that I'd be very happy if you supported.

**Comment by boyang9527** [comment]
Thanks for your feature requirement. 

So far the design is to install to system path, so that every user on the machine will be able to use it.  The installation to user's directory is in backlog, we will consider it in the future.
