### ISSUE TITLE
Provide automatic token refresh for plugins

### ISSUE THREAD

**Issue by mdeuser** [IBM-Cloud/ibm-cloud-cli-sdk#46]
Today, each plugin is responsible for validating the current token(s) it needs and refreshing those expired tokens. Since this is a common plugin practice, this capability could be centralized in the plugin SDK.

Some implementation options:
- Provide a PluginMetadata setting through which the plugin communicates the need for a valid token.  The SDK will then ensure the token(s) are valid when the plugin is invoked.
- Provide an API that validates and optionally refreshes the token

**Comment by boyang9527** [comment]
There is no 100% guarantee we can validate the token locally without server interaction...  you can wrap your http client to do refresh and try again when you get 401, or you just refresh the token no matter it expires or not.

**Comment by mdeuser** [comment]
Won't the plugins require server interaction to validate the token as well?  I think having that validation in a central spot would be helpful for plugin development on a non-default, by-configuration basis.

**Comment by boyang9527** [comment]
we don't know whether the token is valid or not unless we try to access a resource with the token and get a 401.   ( You can decode the token and get expire time but there is no guarantee).   

One solution is we enhance the http/rest client to be able to pass in a token refresher, and the client will do fresh and try again if it gets 401. Then from plugin, it only needs to pass in the token refresh when creating the client, or pass nothing which indicates not doing that automatically.

**Comment by mdeuser** [comment]
Yes, that is the same dilemma each plugin faces - how to ensure the token is valid.

In the above description, does "client" refer to the plugin SDK?  I'm thinking so, but wanted to confirm.

For plugins that do not leverage the SDK's http client, having a standalone "get valid token" method in addition to the embedded http/client token refresh would be helpful.

**Comment by mdeuser** [comment]
Here's a go package that might be useful in determining if the token has expired without requiring a connection to a back-end endpoint
https://godoc.org/github.com/dgrijalva/jwt-go

**Comment by JunliWang** [comment]
from https://github.com/dgrijalva/jwt-go/blob/master/errors.go, the validation by this library is just checking standard claims, while services from Bluemix may perform other validations that we can't do in cli-sdk, eg. grant_type is expected, iam id exists, account is not suspended, etc

**Comment by mdeuser** [comment]
@JunliWang - good points.  although, i'm thinking that once a token is in hand and has been presumably validated, is the most common reason for needing to refresh a token due to the token being expired.  in any case, i think token validation is a common service that seems best located in the plugin sdk as opposed to having each plugin implement the same check/refresh logic,

**Comment by mdeuser** [comment]
@JunliWang - what do you think about providing a `token expired` sdk api?

**Comment by boyang9527** [comment]
will not do it while user can have its own logic to check whether the token is expired
