### ISSUE TITLE
setting namespace to any other valid namespace is ignored

### ISSUE THREAD

**Issue by pritidesai** [IBM-Cloud/ibm-cloud-cli-sdk#73]
```
bx wsk property get --namespace
whisk namespace		_

bx wsk property set --namespace <namespace>
ok: whisk namespace set to <namespace>

bx wsk property get --namespace
whisk namespace		_
```

```
bx -v
bx version 0.6.1+724c406b-2017-10-09T03:12:39+00:00
```

P.S. I am not sure where this should be reported, I found this repo as a best fit for now.

**Comment by boyang9527** [comment]
This is about whisk cli plugin, not about SDK issue.  It has been a while so if you still have the issue, pls reopen the issue and I can forwarded to whisk cli contact.
