### ISSUE TITLE
Excessive spaces at the end of each line

### ISSUE THREAD

**Issue by archerzz** [IBM-Cloud/ibm-cloud-cli-sdk#77]
# Problem
It seems that for every line in the console output, there is two spaces at the end. This will cause problems for testing or automation scripts which uses pattern matching (like regular expression).
![image](https://user-images.githubusercontent.com/4516/32609557-05a2e992-c59b-11e7-883d-bc61f9984680.png)

**Comment by weieigao** [comment]
@archerzz  I cannot reproduce it on my side. Please give more details.

**Comment by weieigao** [comment]
@archerzz  I  think I  get your point now. 

It's by design... If the cell width is less than the max column width, it'll be filled with padding (space) even it's the last column.
