### ISSUE TITLE
Run in non-interactive mode

### ISSUE THREAD

**Issue by sagikazarmark** [IBM-Cloud/ibm-cloud-cli-sdk#87]
Regardless of the possibility to turn off version checks (#86), I think a non-interactive mode would still be a nice feature.

Our use case is running the CLI in CI processes. After a build succeeds we deploy the application to a k8s cluster. To do that we need the cluster config.

With the version check turned off and providing every option it's somewhat a good compromise, but if there is ever a change that requires additional information or different options the process will hang instead of failing since it interactively asks a question and waits for the answer.

A no-interactive option would solve that problem.

**Comment by boyang9527** [comment]
`sudo bx update -f` will update the cli without confirmation.

**Comment by sagikazarmark** [comment]
@boyang9527 Thanks, but that's not what I meant. I don't want to update the CLI, just run it. (Part of the story is that I run it in a container).

The problem is that there is no way to force a non interactive mode, thus there is always a chance (update available, some information not provided as a CLI option/argument) that the process will simply hang and wait for an answer.

That doesn't work in CI.

**Comment by boyang9527** [comment]
@sagikazarmark  We don't have non-interactive setting right now...while for each command, you should be able to do it non-interactively by setting a config or with an option (something like -f / --force). 

we are considering to refactoring the terminal UI utility so that we can have a common library to support non-interactive mode, also similar thing like --quiet

**Comment by GeorgeMac** [comment]
Just want to pitch in another experience report and 👍 for something like this. I work for @codeship and we have customers that want to integrate with your platform via the CLI. Often wanting to pin the version of the CLI tool they are using and script their release process. When prompts happen in CI, it often presents itself as just a stuck build in your system. The build just hangs until the CI reaches some timeout.

The work around we are giving our customers currently is to pin the version they want use `yes n` (e.g. `yes n | bluemix ...`) for a no upgrade to all subsequent prompts for now. While this works it can be confusing for customers to know they need to configure it this way. Would be awesome if we could even get a "prompting for update" message flushed to STDOUT before the prompt to guide users to the problem quicker :)

**Comment by boyang9527** [comment]
@GeorgeMac  thanks for the feedback. Here are a few things that may help. 

1) the version check for upgrade can be disable by running `ibmcloud config --check-version false`.  With this configure, you will not be prompted or update
2) If you always want to get latest version in your script,  use `sudo bx update -f`. This will force upgrade without confirmation.  `sudo` is required if the user is not root.

**Comment by boyang9527** [comment]
@GeorgeMac let me clarify a little bit, you mean "prompt for update" sent to STDOUT even the version check is disabled? 
By the way, if you want to stay with the current version without update,  why not just disable it by 'ibmcloud config --check-version false'

**Comment by GeorgeMac** [comment]
Oh I did not know that was possible. Thank you for that! That solves my use-case completely 🙇

**Comment by GeorgeMac** [comment]
I also read that flag as being passable to any command (the `--check-version false` flag) at first. So I attempted that and it failed. My fault. Not paying enough attention.

**Comment by boyang9527** [comment]
you can set environment variable for a specific command: 

`BLUEMIX_VERSION_CHECK=false ibmcloud login`
