### ISSUE TITLE
Provide option for hidden commands and flags

### ISSUE THREAD

**Issue by stiggity** [IBM-Cloud/ibm-cloud-cli-sdk#93]
We'd like to make a change to some commands and flags, but we'd need to support the older versions of each for backward compatibility. However, I'd like the older versions to not appear in the help.

**Comment by boyang9527** [comment]
@weieigao  can we add this to SDK too, given we already have this capability in base CLI

**Comment by weieigao** [comment]
@boyang9527  it's doable.
