### ISSUE TITLE
Allow use of backticks (`)

### ISSUE THREAD

**Issue by Rachael-Graham** [IBM-Cloud/ibm-cloud-cli-sdk#94]
Hi there--I've noticed that back ticks (\`) do not render in the CLI at all. Bluemix Style requires backticks in some situations, and using single quotes isn't sufficient. When I replaced any single quotes (') with (`), the output didn't show the punctuation at all. We've tried a few other things (like replacing with \&#96;) and still nothing renders.

Would like to be able to use this functionality. Thanks!

**Comment by boyang9527** [comment]
@weieigao  pls help take a look at this request.

**Comment by weieigao** [comment]
@Rachael-Graham could you give more details? CLI should have no special handling of text.

**Comment by Rachael-Graham** [comment]
Sure! So when I am editing strings in the [command_metadata.go](https://github.ibm.com/alchemy-containers/armada-cli/blob/master/plugin/models/command_metadata.go) file for the bx cs plug-in (I'm a tech writer for containers), I sometimes need to reference other commands, flags, or values in the strings. IBM Style dictates that we use backticks when referencing commands, values, or flags in strings. But when I use a backtick, it does not appear at all in the CLI. 

For example, in this [description](https://github.ibm.com/alchemy-containers/armada-cli/blob/master/plugin/models/command_metadata.go#L542) for a flag, I reference a command, but am having to surround it with single quotes:

```
cli.StringFlag{
	Name:  "private-vlan",
	Usage: i18n.T("The ID of the private VLAN. To see available VLANs, run 'bx cs vlans <location>'."),
		},
```
Or in this [description ](https://github.ibm.com/alchemy-containers/armada-cli/blob/master/plugin/models/command_metadata.go#L813)for a flag, I reference accepted values.
```
cli.StringFlag{
	Name:  "level",
	Usage: i18n.T("Set the notification level. Accepted values are 'Normal' or 'Warning'. The default is 'Warning'."),
		},
```

Would like to be able to use backticks instead of having to use single quotes in this situation.

**Comment by weieigao** [comment]
The CLI takes the description as a normal string, not a markdown string...I think Bluemix Style only refers to doc, not the command help...

**Comment by Rachael-Graham** [comment]
Okay. Thought I'd check and see. Thanks
